DROP TABLE BCAS_PRODUCERSTMTHEADER;
DROP TABLE BCAS_ACTIVITIES;
DROP TABLE BCAS_PAYMENTS;

CREATE TABLE BCAS_PRODUCERSTMTHEADER
(
  PRODUCERPUBLICID VARCHAR2(20),
  STMTDATE TIMESTAMP(6),
  TOTALACTIVITYAMT NUMBER(18,2),
  TOTALBASISAMT NUMBER(18,2),
  TOTALPAYMENTAMT NUMBER(18,2)
);

CREATE TABLE BCAS_ACTIVITIES
(
  PRODUCERPUBLICID VARCHAR2(20),
  STMTDATE TIMESTAMP(6),
  POLICYNUMBER VARCHAR2(255),
  ACCOUNTNUMBER VARCHAR2(255),
  ITEMEVENTDATE TIMESTAMP(6),
  EVENT VARCHAR2(256),
  INVOICEITEMTYPE VARCHAR2(256),
  CHARGEID NUMBER,
  EVENTDATE TIMESTAMP(6),
  BASIS NUMBER(18,2),
  CHARGENAME VARCHAR2(256),
  TRANSACTIONID NUMBER,
  TRANSACTIONAMT NUMBER(18,2)
);

CREATE TABLE BCAS_PAYMENTS
(
  PRODUCERPUBLICID VARCHAR2(20),
  STMTDATE TIMESTAMP(6),
  POLICYNUMBER VARCHAR2(255),
  CONTEXT VARCHAR2(256),
  TRANSACTIONAMT NUMBER(18,2),
  TRANSACTIONDATE TIMESTAMP(6),
  TRANSACTIONNUMBER VARCHAR2(255)
);

commit;